// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace passwordChecker.WebAPI.Client
{
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Password.
    /// </summary>
    public static partial class PasswordExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='password'>
            /// </param>
            public static int? CheckPassword(this IPassword operations, string password = default(string))
            {
                return operations.CheckPasswordAsync(password).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='password'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<int?> CheckPasswordAsync(this IPassword operations, string password = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CheckPasswordWithHttpMessagesAsync(password, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
